# Generated by Django 4.2.15 on 2024-08-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-created_on']},
        ),
    ]
